### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by zakqwy** [NeuroTinker/NeuroBytes_Interneuron#1]
The /scripts directory has a few unrelated *.html files. Also getting a lot of compilation warnings.

**Comment by jrwhite** [comment]
I've just pushed some changes to clean up the firmware quite a bit.
Redundant and commented code has been removed and the /scripts directory has been removed entirely. 
Comments and explanations of code sections have been added although there is still some work to be done on this.
The code should compile with only one warning now which is about the the 'sender_id' variable being declared but not used. For right now, I've left it in as it makes the parsing of incoming messages more clear to a reader.
