### ISSUE TITLE
multiple inhibitory signals eventually cause action potential

### ISSUE THREAD

**Issue by zakqwy** [NeuroTinker/NeuroBytes_Interneuron#7]

**Comment by jrwhite** [comment]
this has been fixed in the new firmware.

**Comment by NeuroTinkerJoe** [comment]
This still is a problem on the newest firmware (at least the newest that I have access to). Reflashed an interneuron just to be sure. With strong inhibition coming in through a short, high strength, dendrite, the interneuron fires repeated action potentials when it should be held at a hyperpolarized potential.
