### ISSUE TITLE
Temporal Summation

### ISSUE THREAD

**Issue by NeuroTinkerJoe** [NeuroTinker/NeuroBytes_Interneuron#8]
Weighting of #4 short dendrite is less than weighting of #1 short dendrite. An incoming AP on #1 always leads to firing, whereas two APs in quick succession are needed on #4 to fire an AP. 

The weighting of dendrites #2 and #3 seems to be too low, APs can not be fired even with rapid signals coming into these dendrites. 

In addition, the LED color change from green to yellow with a subthreshold increase in membrane potential is difficult to see, it looks more like a flickering of the green LED.

**Comment by jrwhite** [comment]
Changed to:
1 - 150%
2- 60%
3- 60%
4 - 110%

Let me know if you want these tweaked
